---
- name: "Altera tempo de retencao do syslog, auth, messages e outros para 6 meses"
  block:
    - name: "Altera tempo de rotacao)"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: 'rotate(.+)'
        replace: 'rotate 27'
      loop:
        - /etc/logrotate.d/rsyslog
        - /etc/logrotate.d/sssd-common

    - name: "Altera tempo de frequencia)"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: 'daily'
        replace: 'weekly'
      loop:
        - /etc/logrotate.d/rsyslog
        - /etc/logrotate.d/sssd-common
